application: valkyrie-1190
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
- url: /static
  static_dir: static
  application_readable: true

libraries:
- name: django
  version: "latest"
