application: mealsloth-valkyrie-ap01
version: 1
runtime: python27
api_version: 1
threadsafe: true


skip_files:
- ^(.*/)?.*\.pyc$
- ^(.*/)?.*\.less$
- ^(.*/)?.*\.pack$
- ^(.*/)?.*\.DS_Store$
- ^(.*/)?.*\.csslintrc$
- ^(.*/)?.*/\.idea/.*$
- ^(.*/)?.*/Siren/static/.*$


handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
- url: /static
  static_dir: static
  application_readable: true
- url: /.*
  script: main.app


libraries:
- name: django
  version: "latest"
- name: MySQLdb
  version: "latest"